### ISSUE TITLE
Fix broken test script

### ISSUE THREAD

**Issue by felipelauten** [felipelauten/lottery-algorithm#3]
I added the missing dependencies to Jest, Mocha and other types.
Also created the jest configuration according to this [link](https://jestjs.io/docs/getting-started).

However, there was a problem in building the project running it from `npm test` (I fixed also the package.json). It doesn't find some jest classes. So I moved to the `src` folder as recommended by the terminal output.
But now, the build process is fixed, but the test is broken.

Please investigate and fix.

**Comment by krisJagoda** [comment]
Is it the expectation to execute the lottery-application.test.ts file rather than the following (I've added the test coverage statistics, I hope thats ok):
PASS  build/__tests__/unit/lottery-application.test.js
-------------------------|---------|----------|---------|---------|-------------------
File                     | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-------------------------|---------|----------|---------|---------|-------------------
All files                |   35.18 |    83.33 |    7.69 |   35.84 |                   
 build                   |   36.11 |    83.33 |   16.66 |   37.14 |                   
  lottery-application.js |   36.11 |    83.33 |   16.66 |   37.14 | 19-49             
 build/algorithms        |      30 |      100 |       0 |      30 |                   
  algorithm-v1.js        |      30 |      100 |       0 |      30 | 6-21              
 build/utils             |    37.5 |      100 |       0 |    37.5 |                   
  stopwatch.js           |    37.5 |      100 |       0 |    37.5 | 6-16              
-------------------------|---------|----------|---------|---------|-------------------

Test Suites: 1 failed, 1 passed, 2 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        0.623 s


'The TypeScript jest error "Cannot use import statement outside module" occurs when jest is misconfigured in a TypeScript project. To solve the error, you have to make sure that your TypeScript files are compiled to JavaScript before they are run because jest on its own cannot understand TypeScript.'

I can try to find the way round it if this is the expectation to execute the unit/integration tests before creating the production build :)

**Comment by felipelauten** [comment]
@krisJagoda, please review. You can checkout on your env and see if it works for you.
